'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PatchInstaller

    '''<summary>
    '''FrmPatchInstaller control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FrmPatchInstaller As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''LangLeftLnkInstPatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LangLeftLnkInstPatch As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lang_db_PatchMainHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lang_db_PatchMainHeading As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lang_db_Patch_subHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lang_db_Patch_subHead As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''aLogFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aLogFile As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''imgInstPatchTickGray control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgInstPatchTickGray As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''imgInstPatchProcessing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgInstPatchProcessing As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''imgInstPatchTick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgInstPatchTick As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''imgInstPatchError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgInstPatchError As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''langInstallingPatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents langInstallingPatch As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BtnInstall_Patch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnInstall_Patch As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''LangPatchInstSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LangPatchInstSuccess As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''LangPatchInstFailed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LangPatchInstFailed As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''LangPatchLngSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LangPatchLngSuccess As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''LangPatchLngError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LangPatchLngError As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''LangPatchSetSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LangPatchSetSuccess As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''LangPatchSetError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LangPatchSetError As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
