//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevInfo.Lib.DI_LibBAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevInfo.Lib.DI_LibBAL.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;root&gt;
        ///
        ///	&lt;Input1&gt;
        ///		&lt;ID&gt;MD_IND_1&lt;/ID&gt;
        ///		&lt;Path&gt;Indicator_Info/Row1/FLD_VAL/RowData/temp1&lt;/Path&gt;
        ///		&lt;Position&gt;1/1/1/n/1&lt;/Position&gt;
        ///		&lt;Type&gt;Element&lt;/Type&gt;
        ///		&lt;Caption lang=&quot;en&quot;&gt;Definition&lt;/Caption&gt;
        ///		&lt;Caption lang=&quot;fr&quot;&gt;Definition&lt;/Caption&gt;
        ///		&lt;Caption lang=&quot;zh&quot;&gt;Definition&lt;/Caption&gt;
        ///		&lt;Caption lang=&quot;ar&quot;&gt;Definition&lt;/Caption&gt;
        ///		&lt;Caption lang=&quot;es&quot;&gt;Definition&lt;/Caption&gt;
        ///		&lt;Caption lang=&quot;ru&quot;&gt;Definition&lt;/Caption&gt;
        ///	&lt;/Input1&gt;
        ///
        ///	&lt;Input2&gt;
        ///		&lt;ID&gt;MD_IND_2&lt;/ID&gt;
        ///		&lt;Path&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultIndMask {
            get {
                return ResourceManager.GetString("DefaultIndMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;root&gt;
        ///
        ///	&lt;Input1&gt;
        ///		&lt;ID&gt;MD_AREA_1&lt;/ID&gt;
        ///		&lt;Path&gt;Indicator_Info/Row1/FLD_VAL/RowData/temp1&lt;/Path&gt;
        ///		&lt;Position&gt;1/1/1/n/1&lt;/Position&gt;
        ///		&lt;Type&gt;Element&lt;/Type&gt;
        ///		&lt;Caption lang=&quot;en&quot;&gt;Dataset Title&lt;/Caption&gt;
        ///		&lt;Caption lang=&quot;fr&quot;&gt;Dataset Title&lt;/Caption&gt;
        ///		&lt;Caption lang=&quot;zh&quot;&gt;Dataset Title&lt;/Caption&gt;
        ///		&lt;Caption lang=&quot;ar&quot;&gt;Dataset Title&lt;/Caption&gt;
        ///		&lt;Caption lang=&quot;es&quot;&gt;Dataset Title&lt;/Caption&gt;
        ///		&lt;Caption lang=&quot;ru&quot;&gt;Dataset Title&lt;/Caption&gt;
        ///	&lt;/Input1&gt;
        ///
        ///	&lt;Input2&gt;
        ///		&lt;ID&gt;MD_A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultMapMask {
            get {
                return ResourceManager.GetString("DefaultMapMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;root&gt;
        ///
        ///	&lt;Input1&gt;
        ///		&lt;ID&gt;MD_SRC_1&lt;/ID&gt;
        ///		&lt;Path&gt;Indicator_Info/Row1/FLD_VAL/RowData/temp1&lt;/Path&gt;
        ///		&lt;Position&gt;1/1/1/n/1&lt;/Position&gt;
        ///		&lt;Type&gt;Element&lt;/Type&gt;
        ///		&lt;Caption lang=&quot;en&quot;&gt;Publisher&lt;/Caption&gt;
        ///		&lt;Caption lang=&quot;fr&quot;&gt;Publisher&lt;/Caption&gt;
        ///		&lt;Caption lang=&quot;zh&quot;&gt;Publisher&lt;/Caption&gt;
        ///		&lt;Caption lang=&quot;ar&quot;&gt;Publisher&lt;/Caption&gt;
        ///		&lt;Caption lang=&quot;es&quot;&gt;Publisher&lt;/Caption&gt;
        ///		&lt;Caption lang=&quot;ru&quot;&gt;Publisher&lt;/Caption&gt;
        ///	&lt;/Input1&gt;
        ///
        ///	&lt;Input2&gt;
        ///		&lt;ID&gt;MD_SRC_2&lt;/ID&gt;
        ///		&lt;Path&gt;Indica [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultSrcMask {
            get {
                return ResourceManager.GetString("DefaultSrcMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalInArabic {
            get {
                return ResourceManager.GetString("TotalInArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalInChinese {
            get {
                return ResourceManager.GetString("TotalInChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalInEnglish {
            get {
                return ResourceManager.GetString("TotalInEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalInFrench {
            get {
                return ResourceManager.GetString("TotalInFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего.
        /// </summary>
        internal static string TotalInRussian {
            get {
                return ResourceManager.GetString("TotalInRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalInSpanish {
            get {
                return ResourceManager.GetString("TotalInSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; indent=&quot;yes&quot;/&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;STYLE type=&quot;text/css&quot;&gt;
        ///          .HeaderItems
        ///          {
        ///          font-size: 9pt;
        ///          color: black;
        ///          font-family: Arial, Verdana, Helvetica, sans-serif;
        ///          font-weight:bold;
        ///          background-color:#cccccc;
        ///          }        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSLT_DI6 {
            get {
                return ResourceManager.GetString("XSLT_DI6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; &gt;
        ///  &lt;xsl:output method=&quot;xml&quot; version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; indent=&quot;yes&quot;/&gt;
        ///  &lt;xsl:template match=&quot;*&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;STYLE type=&quot;text/css&quot;&gt;
        ///          .HeaderItems
        ///          {
        ///          font-size: 9pt;
        ///          color: black;
        ///          font-family: Arial, Verdana, Helvetica, sans-serif;
        ///          font-weight:bold;
        ///          background-color:#cccccc;
        ///          } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSLTFile2 {
            get {
                return ResourceManager.GetString("XSLTFile2", resourceCulture);
            }
        }
    }
}
