//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMXApi_2_1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDMXApi_2_1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2010 - http://www.sdmx.org --&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common&quot; elementFormDefault=&quot;qualified&quot; xmlns=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;!-- Note: The following import statement sometimes causes problems with IE 6.* If you have this problem, comment it out. --&gt;
        ///  &lt;xs:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot; s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXCommon {
            get {
                return ResourceManager.GetString("SDMXCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2010 - http://www.sdmx.org --&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns:common=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common&quot;
        ///           xmlns=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/data/generic&quot;
        ///           targetNamespace=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/data/generic&quot;
        ///           elementFormDefault=&quot;qualified&quot;&gt;
        ///  &lt;xs:import namespace=&quot;http://www.sdmx.org/resources/sdmxml [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXDataGeneric {
            get {
                return ResourceManager.GetString("SDMXDataGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2010 - http://www.sdmx.org --&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/data/structurespecific&quot;
        ///           xmlns:common=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common&quot;
        ///           elementFormDefault=&quot;qualified&quot;
        ///           targetNamespace=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/data/structurespecific&quot;&gt;
        ///  &lt;xs:import namespace=&quot;http://www.sdmx. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXDataStructureSpecific {
            get {
                return ResourceManager.GetString("SDMXDataStructureSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2010 - http://www.sdmx.org --&gt;
        ///&lt;xs:schema xmlns=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message&quot; xmlns:message=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message&quot; targetNamespace=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message&quot; xmlns:footer=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message/footer&quot; xmlns:common=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common&quot; xmlns:structure=&quot;http://www.sdmx.org/reso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXMessage {
            get {
                return ResourceManager.GetString("SDMXMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2010 - http://www.sdmx.org --&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message/footer&quot; xmlns=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message/footer&quot; xmlns:common=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///  &lt;xs:import namespace=&quot;http://www.sdmx.org/resources/s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXMessageFooter {
            get {
                return ResourceManager.GetString("SDMXMessageFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2010 - http://www.sdmx.org --&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/metadata/generic&quot;
        ///           xmlns:common=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common&quot;
        ///           targetNamespace=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/metadata/generic&quot;
        ///           elementFormDefault=&quot;qualified&quot;&gt;
        ///  &lt;xs:import namespace=&quot;http://www.sdmx.org/resource [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXMetadataGeneric {
            get {
                return ResourceManager.GetString("SDMXMetadataGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2010 - http://www.sdmx.org --&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/metadata/structurespecific&quot;
        ///           xmlns=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/metadata/structurespecific&quot;
        ///           xmlns:common=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common&quot;
        ///           xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           elementFormDefault=&quot;qualified&quot;&gt;
        ///  &lt;xs:import namespace=&quot;http://w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXMetadataStructureSpecific {
            get {
                return ResourceManager.GetString("SDMXMetadataStructureSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2010 - http://www.sdmx.org --&gt;
        ///&lt;xs:schema elementFormDefault=&quot;qualified&quot;
        ///           targetNamespace=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/query&quot;
        ///           xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/query&quot;
        ///           xmlns:query=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/query&quot;
        ///           xmlns:common=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXQuery {
            get {
                return ResourceManager.GetString("SDMXQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2010 - http://www.sdmx.org --&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/registry&quot;
        ///           elementFormDefault=&quot;qualified&quot;
        ///           xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/registry&quot;
        ///           xmlns:common=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common&quot;
        ///           xmlns:structure=&quot;http://www.sdmx.org/resources/sdmxml/sche [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXRegistry {
            get {
                return ResourceManager.GetString("SDMXRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2010 - http://www.sdmx.org --&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/structure&quot;
        ///           elementFormDefault=&quot;qualified&quot;
        ///           xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/structure&quot;
        ///           xmlns:structure=&quot;http://www.sdmx.org/resources/sdmxml/schemas/v2_1/structure&quot;
        ///           xmlns:common=&quot;http://www.sdmx.org/resources/sdmxml [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXStructure {
            get {
                return ResourceManager.GetString("SDMXStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos;?&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.w3.org/XML/1998/namespace&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xml:lang=&quot;en&quot;&gt;
        ///
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;
        ///      See http://www.w3.org/XML/1998/namespace.html and
        ///      http://www.w3.org/TR/REC-xml for information about this namespace.
        ///    &lt;/xs:documentation&gt;
        ///  &lt;/xs:annotation&gt;
        ///
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;
        ///      This schema defines attributes and an attribute group
        ///      suitable for use by
        ///      sch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml {
            get {
                return ResourceManager.GetString("xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.w3.org/2001/XMLSchema&quot; blockDefault=&quot;#all&quot; elementFormDefault=&quot;qualified&quot; version=&quot;1.0&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xml:lang=&quot;EN&quot; xmlns:hfp=&quot;http://www.w3.org/2001/XMLSchema-hasFacetAndProperty&quot;&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;
        ///      Part 1 version: Id: structures.xsd,v 1.2 2004/01/15 11:34:25 ht Exp
        ///      Part 2 version: Id: datatypes.xsd,v 1.3 2004/01/23 18:11:13 ht Exp
        ///    &lt;/xs:documentation&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLSchema {
            get {
                return ResourceManager.GetString("XMLSchema", resourceCulture);
            }
        }
    }
}
