
di_jq.widget("daredevel.checkboxTree",{_allDescendantChecked:function(li){return(li.parents('li:first').find('li input:checkbox:not(:checked)').length==0);},_create:function(){var t=this
if(this.options.collapsable){this.options.collapseAnchor=(this.options.collapseImage.length>0)?'<img src="'+this.options.collapseImage+'" />':'';this.options.expandAnchor=(this.options.expandImage.length>0)?'<img src="'+this.options.expandImage+'" />':'';this.options.leafAnchor=(this.options.leafImage.length>0)?'<img src="'+this.options.leafImage+'" />':'';this.element.find("li:has(ul):has(input:checkbox:checked)").each(function(){di_jq(this).prepend(di_jq('<span />'));t.options.initializeChecked=='collapsed'?t.collapse(di_jq(this)):t.expand(di_jq(this));});this.element.find("li:has(ul):not(:has(input:checkbox:checked))").each(function(){di_jq(this).prepend(di_jq('<span />'));t.options.initializeUnchecked=='collapsed'?t.collapse(di_jq(this)):t.expand(di_jq(this));});this.element.find('li span').live("click",function(){li=di_jq(this).parents("li:first");if(li.hasClass('collapsed')){t.expand(li);}else
if(li.hasClass('expanded')){t.collapse(li);}});this.element.find('li label').live("click",function(){li=di_jq(this).parents("li:first");if(li.hasClass('collapsed')){t.expand(li);}else
if(li.hasClass('expanded')){t.collapse(li);}});di_jq(this.options.collapseAllElement).bind("click",function(){t.collapseAll();});di_jq(this.options.expandAllElement).bind("click",function(){t.expandAll();});if(this.options.onUncheck.node=='collapse'){this.element.find('input:checkbox:not(:checked)').live("click",function(){t.collapse(di_jq(this).parents("li:first"));});}else
if(this.options.onUncheck.node=='expand'){this.element.find('input:checkbox:not(:checked)').live("click",function(){t.expand(di_jq(this).parents("li:first"));});}
if(this.options.onCheck.node=='collapse'){this.element.find('input:checkbox:checked').live("click",function(){t.collapse(di_jq(this).parents("li:first"));});}else
if(this.options.onCheck.node=='expand'){this.element.find('input:checkbox:checked').live("click",function(){t.expand(di_jq(this).parents("li:first"));});}}
this.element.find('input:checkbox:not(:checked)').live('click',function(){var li=di_jq(this).parents('li:first');if(t.options.trueCheck.val=='yes')
t.uncheck(li);});this.element.find('input:checkbox:checked').live('click',function(){var li=di_jq(this).parents('li:first');if(t.options.trueCheck.val=='yes')
t.check(li);});this.element.addClass('ui-widget-daredevel-checkboxTree');this.element.addClass('ui-widget ui-widget-content');},_checkAncestors:function(li){li.parentsUntil(".ui-widget").filter('li').find('input:checkbox:first:not(:checked)').attr('checked','checked').change();},_checkDescendants:function(li){li.find('li input:checkbox:not(:checked)').attr('checked','checked').change();},_checkOthers:function(li){var t=this;li.addClass('exclude');li.parents('li').addClass('exclude');li.find('li').addClass('exclude');di_jq(this.element).find('li').each(function(){if(!di_jq(this).hasClass('exclude')){di_jq(this).find('input:checkbox:first:not(:checked)').attr('checked','checked').change();}});di_jq(this.element).find('li').removeClass('exclude');},_destroy:function(){this.element.removeClass(this.options.cssClass);di_jq.Widget.prototype.destroy.call(this);},_isRoot:function(li){return li.parents('ul:first')==this.element;},_markAsCollapsed:function(li){if(this.options.expandAnchor.length>0){li.children("span").html(this.options.expandAnchor);}else
if(this.options.collapseUiIcon.length>0){li.children("span").removeClass(this.options.expandUiIcon).addClass('ui-icon '+this.options.collapseUiIcon);}
li.removeClass("expanded").addClass("collapsed");},_markAsExpanded:function(li){if(this.options.collapseAnchor.length>0){li.children("span").html(this.options.collapseAnchor);}else
if(this.options.expandUiIcon.length>0){li.children("span").removeClass(this.options.collapseUiIcon).addClass('ui-icon '+this.options.expandUiIcon);}
li.removeClass("collapsed").addClass("expanded");},_markAsLeaf:function(li){if(this.options.leafAnchor.length>0){li.children("span").html(this.options.leafAnchor);}else
if(this.options.leafUiIcon.length>0){li.children("span").addClass('ui-icon '+this.options.leafUiIcon);}
li.addClass("leaf");},_parentNode:function(li){return li.parents('li:first');},_uncheckAncestors:function(li){li.parentsUntil(".ui-widget").filter('li').find('input:checkbox:first:checked').attr('checked','').change();},_uncheckDescendants:function(li){li.find('li input:checkbox:checked').attr('checked','').change();},_uncheckOthers:function(li){var t=this;li.addClass('exclude');li.parents('li').addClass('exclude');li.find('li').addClass('exclude');di_jq(this.element).find('li').each(function(){if(!di_jq(this).hasClass('exclude')){di_jq(this).find('input:checkbox:first:checked').attr('checked','').change();}});di_jq(this.element).find('li').removeClass('exclude');},check:function(li){li.find('input:checkbox:first:not(:checked)').attr('checked','checked').change();if(this.options.onCheck.others=='check'){this._checkOthers(li);}else
if(this.options.onCheck.others=='uncheck'){this._uncheckOthers(li);}
if(this.options.onCheck.descendants=='check'){this._checkDescendants(li);}else
if(this.options.onCheck.descendants=='uncheck'){this._uncheckDescendants(li);}
if(this.options.onCheck.ancestors=='check'){this._checkAncestors(li);}else
if(this.options.onCheck.ancestors=='uncheck'){this._uncheckAncestors(li);}else
if(this.options.onCheck.ancestors=='checkIfFull'){if(this._allDescendantChecked(li)&&!this._isRoot(li)){this.check(this._parentNode(li));}}},checkAll:function(){di_jq(this.element).find('input:checkbox:not(:checked)').attr('checked','checked').change();},collapse:function(li){if(li.hasClass('collapsed')||(li.hasClass('leaf'))){return;}
var t=this;li.children("ul").hide(this.options.collapseEffect,{},this.options.collapseDuration);setTimeout(function(){t._markAsCollapsed(li,t.options);},t.options.collapseDuration);t._trigger('collapse',li);},collapseAll:function(){var t=this;di_jq(this.element).find('li.expanded').each(function(){t.collapse(di_jq(this));});},expand:function(li){if(li.hasClass('expanded')||(li.hasClass('leaf'))){return;}
var t=this;li.children("ul").show(t.options.expandEffect,{},t.options.expandDuration);setTimeout(function(){t._markAsExpanded(li,t.options);},t.options.expandDuration);t._trigger('expand',li);},expandAll:function(){var t=this;di_jq(this.element).find('li.collapsed').each(function(){t.expand(di_jq(this));});},uncheck:function(li){li.find('input:checkbox:first:checked').attr('checked','').change();if(this.options.onUncheck.others=='check'){this._checkOthers(li);}else
if(this.options.onUncheck.others=='uncheck'){this._uncheckOthers(li);}
if(this.options.onUncheck.descendants=='check'){this._checkDescendants(li);}else
if(this.options.onUncheck.descendants=='uncheck'){this._uncheckDescendants(li);}
if(this.options.onUncheck.ancestors=='check'){this._checkAncestors(li);}else
if(this.options.onUncheck.ancestors=='uncheck'){this._uncheckAncestors(li);}},uncheckAll:function(){di_jq(this.element).find('input:checkbox:checked').attr('checked','').change();},options:{collapsable:true,collapseAllElement:'',collapseDuration:500,collapseEffect:'blind',collapseImage:'',collapseUiIcon:'ui-icon-triangle-1-e',expandAllElement:'',expandDuration:500,expandEffect:'blind',expandImage:'',expandUiIcon:'ui-icon-triangle-1-se',initializeChecked:'expanded',initializeUnchecked:'expanded',leafImage:'',leafUiIcon:'',onCheck:{ancestors:'check',descendants:'check',node:'',others:''},onUncheck:{ancestors:'',descendants:'uncheck',node:'',others:''}}});