//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace DevInfo.Lib.DI_LibBAL.SDMXRegistry {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RegistryServiceSoap", Namespace="http://www.devinfo.info/")]
    public partial class RegistryService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetStructureSpecificMetadataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitStructureOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportingTaxonomyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStructureSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProcessOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHierarchicalCodelistOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataSchemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMetadataSchemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataflowOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMetadataflowOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataStructureOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMetadataStructureOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCategorySchemeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCategorisationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConceptSchemeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCodelistOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrganisationSchemeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProvisionAgreementOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConstraintOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStructuresOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitSubscriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuerySubscriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitRegistrationOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryRegistrationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGenericDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGenericTimeSeriesDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStructureSpecificDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStructureSpecificTimeSeriesDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGenericMetadataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RegistryService() {
            this.Url = global::DevInfo.Lib.DI_LibBAL.Properties.Settings.Default.DI7_LibBAL_SDMXRegistry_RegistryService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetStructureSpecificMetadataCompletedEventHandler GetStructureSpecificMetadataCompleted;
        
        /// <remarks/>
        public event SubmitStructureCompletedEventHandler SubmitStructureCompleted;
        
        /// <remarks/>
        public event GetReportingTaxonomyCompletedEventHandler GetReportingTaxonomyCompleted;
        
        /// <remarks/>
        public event GetStructureSetCompletedEventHandler GetStructureSetCompleted;
        
        /// <remarks/>
        public event GetProcessCompletedEventHandler GetProcessCompleted;
        
        /// <remarks/>
        public event GetHierarchicalCodelistCompletedEventHandler GetHierarchicalCodelistCompleted;
        
        /// <remarks/>
        public event GetDataSchemaCompletedEventHandler GetDataSchemaCompleted;
        
        /// <remarks/>
        public event GetMetadataSchemaCompletedEventHandler GetMetadataSchemaCompleted;
        
        /// <remarks/>
        public event GetDataflowCompletedEventHandler GetDataflowCompleted;
        
        /// <remarks/>
        public event GetMetadataflowCompletedEventHandler GetMetadataflowCompleted;
        
        /// <remarks/>
        public event GetDataStructureCompletedEventHandler GetDataStructureCompleted;
        
        /// <remarks/>
        public event GetMetadataStructureCompletedEventHandler GetMetadataStructureCompleted;
        
        /// <remarks/>
        public event GetCategorySchemeCompletedEventHandler GetCategorySchemeCompleted;
        
        /// <remarks/>
        public event GetCategorisationCompletedEventHandler GetCategorisationCompleted;
        
        /// <remarks/>
        public event GetConceptSchemeCompletedEventHandler GetConceptSchemeCompleted;
        
        /// <remarks/>
        public event GetCodelistCompletedEventHandler GetCodelistCompleted;
        
        /// <remarks/>
        public event GetOrganisationSchemeCompletedEventHandler GetOrganisationSchemeCompleted;
        
        /// <remarks/>
        public event GetProvisionAgreementCompletedEventHandler GetProvisionAgreementCompleted;
        
        /// <remarks/>
        public event GetConstraintCompletedEventHandler GetConstraintCompleted;
        
        /// <remarks/>
        public event GetStructuresCompletedEventHandler GetStructuresCompleted;
        
        /// <remarks/>
        public event SubmitSubscriptionCompletedEventHandler SubmitSubscriptionCompleted;
        
        /// <remarks/>
        public event QuerySubscriptionCompletedEventHandler QuerySubscriptionCompleted;
        
        /// <remarks/>
        public event SubmitRegistrationCompletedEventHandler SubmitRegistrationCompleted;
        
        /// <remarks/>
        public event QueryRegistrationCompletedEventHandler QueryRegistrationCompleted;
        
        /// <remarks/>
        public event GetGenericDataCompletedEventHandler GetGenericDataCompleted;
        
        /// <remarks/>
        public event GetGenericTimeSeriesDataCompletedEventHandler GetGenericTimeSeriesDataCompleted;
        
        /// <remarks/>
        public event GetStructureSpecificDataCompletedEventHandler GetStructureSpecificDataCompleted;
        
        /// <remarks/>
        public event GetStructureSpecificTimeSeriesDataCompletedEventHandler GetStructureSpecificTimeSeriesDataCompleted;
        
        /// <remarks/>
        public event GetGenericMetadataCompletedEventHandler GetGenericMetadataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetStructureSpecificMetadata", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetStructureSpecificMetadata([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetStructureSpecificMetadata", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetStructureSpecificMetadataAsync(System.Xml.XmlElement Any) {
            this.GetStructureSpecificMetadataAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetStructureSpecificMetadataAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetStructureSpecificMetadataOperationCompleted == null)) {
                this.GetStructureSpecificMetadataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStructureSpecificMetadataOperationCompleted);
            }
            this.InvokeAsync("GetStructureSpecificMetadata", new object[] {
                        Any}, this.GetStructureSpecificMetadataOperationCompleted, userState);
        }
        
        private void OnGetStructureSpecificMetadataOperationCompleted(object arg) {
            if ((this.GetStructureSpecificMetadataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStructureSpecificMetadataCompleted(this, new GetStructureSpecificMetadataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/SubmitStructure", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SubmitStructure([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("SubmitStructure", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitStructureAsync(System.Xml.XmlElement Any) {
            this.SubmitStructureAsync(Any, null);
        }
        
        /// <remarks/>
        public void SubmitStructureAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.SubmitStructureOperationCompleted == null)) {
                this.SubmitStructureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitStructureOperationCompleted);
            }
            this.InvokeAsync("SubmitStructure", new object[] {
                        Any}, this.SubmitStructureOperationCompleted, userState);
        }
        
        private void OnSubmitStructureOperationCompleted(object arg) {
            if ((this.SubmitStructureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitStructureCompleted(this, new SubmitStructureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetReportingTaxonomy", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetReportingTaxonomy([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetReportingTaxonomy", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportingTaxonomyAsync(System.Xml.XmlElement Any) {
            this.GetReportingTaxonomyAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetReportingTaxonomyAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetReportingTaxonomyOperationCompleted == null)) {
                this.GetReportingTaxonomyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportingTaxonomyOperationCompleted);
            }
            this.InvokeAsync("GetReportingTaxonomy", new object[] {
                        Any}, this.GetReportingTaxonomyOperationCompleted, userState);
        }
        
        private void OnGetReportingTaxonomyOperationCompleted(object arg) {
            if ((this.GetReportingTaxonomyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportingTaxonomyCompleted(this, new GetReportingTaxonomyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetStructureSet", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetStructureSet([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetStructureSet", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetStructureSetAsync(System.Xml.XmlElement Any) {
            this.GetStructureSetAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetStructureSetAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetStructureSetOperationCompleted == null)) {
                this.GetStructureSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStructureSetOperationCompleted);
            }
            this.InvokeAsync("GetStructureSet", new object[] {
                        Any}, this.GetStructureSetOperationCompleted, userState);
        }
        
        private void OnGetStructureSetOperationCompleted(object arg) {
            if ((this.GetStructureSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStructureSetCompleted(this, new GetStructureSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetProcess", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetProcess([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetProcess", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetProcessAsync(System.Xml.XmlElement Any) {
            this.GetProcessAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetProcessAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetProcessOperationCompleted == null)) {
                this.GetProcessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProcessOperationCompleted);
            }
            this.InvokeAsync("GetProcess", new object[] {
                        Any}, this.GetProcessOperationCompleted, userState);
        }
        
        private void OnGetProcessOperationCompleted(object arg) {
            if ((this.GetProcessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProcessCompleted(this, new GetProcessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetHierarchicalCodelist", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetHierarchicalCodelist([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetHierarchicalCodelist", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetHierarchicalCodelistAsync(System.Xml.XmlElement Any) {
            this.GetHierarchicalCodelistAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetHierarchicalCodelistAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetHierarchicalCodelistOperationCompleted == null)) {
                this.GetHierarchicalCodelistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHierarchicalCodelistOperationCompleted);
            }
            this.InvokeAsync("GetHierarchicalCodelist", new object[] {
                        Any}, this.GetHierarchicalCodelistOperationCompleted, userState);
        }
        
        private void OnGetHierarchicalCodelistOperationCompleted(object arg) {
            if ((this.GetHierarchicalCodelistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHierarchicalCodelistCompleted(this, new GetHierarchicalCodelistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetDataSchema", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetDataSchema([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetDataSchema", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataSchemaAsync(System.Xml.XmlElement Any) {
            this.GetDataSchemaAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetDataSchemaAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetDataSchemaOperationCompleted == null)) {
                this.GetDataSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataSchemaOperationCompleted);
            }
            this.InvokeAsync("GetDataSchema", new object[] {
                        Any}, this.GetDataSchemaOperationCompleted, userState);
        }
        
        private void OnGetDataSchemaOperationCompleted(object arg) {
            if ((this.GetDataSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataSchemaCompleted(this, new GetDataSchemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetMetadataSchema", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetMetadataSchema([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetMetadataSchema", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetMetadataSchemaAsync(System.Xml.XmlElement Any) {
            this.GetMetadataSchemaAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetMetadataSchemaAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetMetadataSchemaOperationCompleted == null)) {
                this.GetMetadataSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMetadataSchemaOperationCompleted);
            }
            this.InvokeAsync("GetMetadataSchema", new object[] {
                        Any}, this.GetMetadataSchemaOperationCompleted, userState);
        }
        
        private void OnGetMetadataSchemaOperationCompleted(object arg) {
            if ((this.GetMetadataSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMetadataSchemaCompleted(this, new GetMetadataSchemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetDataflow", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetDataflow([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetDataflow", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataflowAsync(System.Xml.XmlElement Any) {
            this.GetDataflowAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetDataflowAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetDataflowOperationCompleted == null)) {
                this.GetDataflowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataflowOperationCompleted);
            }
            this.InvokeAsync("GetDataflow", new object[] {
                        Any}, this.GetDataflowOperationCompleted, userState);
        }
        
        private void OnGetDataflowOperationCompleted(object arg) {
            if ((this.GetDataflowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataflowCompleted(this, new GetDataflowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetMetadataflow", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetMetadataflow([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetMetadataflow", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetMetadataflowAsync(System.Xml.XmlElement Any) {
            this.GetMetadataflowAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetMetadataflowAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetMetadataflowOperationCompleted == null)) {
                this.GetMetadataflowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMetadataflowOperationCompleted);
            }
            this.InvokeAsync("GetMetadataflow", new object[] {
                        Any}, this.GetMetadataflowOperationCompleted, userState);
        }
        
        private void OnGetMetadataflowOperationCompleted(object arg) {
            if ((this.GetMetadataflowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMetadataflowCompleted(this, new GetMetadataflowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetDataStructure", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetDataStructure([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetDataStructure", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataStructureAsync(System.Xml.XmlElement Any) {
            this.GetDataStructureAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetDataStructureAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetDataStructureOperationCompleted == null)) {
                this.GetDataStructureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataStructureOperationCompleted);
            }
            this.InvokeAsync("GetDataStructure", new object[] {
                        Any}, this.GetDataStructureOperationCompleted, userState);
        }
        
        private void OnGetDataStructureOperationCompleted(object arg) {
            if ((this.GetDataStructureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataStructureCompleted(this, new GetDataStructureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetMetadataStructure", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetMetadataStructure([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetMetadataStructure", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetMetadataStructureAsync(System.Xml.XmlElement Any) {
            this.GetMetadataStructureAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetMetadataStructureAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetMetadataStructureOperationCompleted == null)) {
                this.GetMetadataStructureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMetadataStructureOperationCompleted);
            }
            this.InvokeAsync("GetMetadataStructure", new object[] {
                        Any}, this.GetMetadataStructureOperationCompleted, userState);
        }
        
        private void OnGetMetadataStructureOperationCompleted(object arg) {
            if ((this.GetMetadataStructureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMetadataStructureCompleted(this, new GetMetadataStructureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetCategoryScheme", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetCategoryScheme([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetCategoryScheme", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetCategorySchemeAsync(System.Xml.XmlElement Any) {
            this.GetCategorySchemeAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetCategorySchemeAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetCategorySchemeOperationCompleted == null)) {
                this.GetCategorySchemeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCategorySchemeOperationCompleted);
            }
            this.InvokeAsync("GetCategoryScheme", new object[] {
                        Any}, this.GetCategorySchemeOperationCompleted, userState);
        }
        
        private void OnGetCategorySchemeOperationCompleted(object arg) {
            if ((this.GetCategorySchemeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCategorySchemeCompleted(this, new GetCategorySchemeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetCategorisation", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetCategorisation([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetCategorisation", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetCategorisationAsync(System.Xml.XmlElement Any) {
            this.GetCategorisationAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetCategorisationAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetCategorisationOperationCompleted == null)) {
                this.GetCategorisationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCategorisationOperationCompleted);
            }
            this.InvokeAsync("GetCategorisation", new object[] {
                        Any}, this.GetCategorisationOperationCompleted, userState);
        }
        
        private void OnGetCategorisationOperationCompleted(object arg) {
            if ((this.GetCategorisationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCategorisationCompleted(this, new GetCategorisationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetConceptScheme", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetConceptScheme([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetConceptScheme", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetConceptSchemeAsync(System.Xml.XmlElement Any) {
            this.GetConceptSchemeAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetConceptSchemeAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetConceptSchemeOperationCompleted == null)) {
                this.GetConceptSchemeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConceptSchemeOperationCompleted);
            }
            this.InvokeAsync("GetConceptScheme", new object[] {
                        Any}, this.GetConceptSchemeOperationCompleted, userState);
        }
        
        private void OnGetConceptSchemeOperationCompleted(object arg) {
            if ((this.GetConceptSchemeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConceptSchemeCompleted(this, new GetConceptSchemeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetCodelist", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetCodelist([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetCodelist", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetCodelistAsync(System.Xml.XmlElement Any) {
            this.GetCodelistAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetCodelistAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetCodelistOperationCompleted == null)) {
                this.GetCodelistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCodelistOperationCompleted);
            }
            this.InvokeAsync("GetCodelist", new object[] {
                        Any}, this.GetCodelistOperationCompleted, userState);
        }
        
        private void OnGetCodelistOperationCompleted(object arg) {
            if ((this.GetCodelistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCodelistCompleted(this, new GetCodelistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetOrganisationScheme", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetOrganisationScheme([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetOrganisationScheme", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrganisationSchemeAsync(System.Xml.XmlElement Any) {
            this.GetOrganisationSchemeAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetOrganisationSchemeAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetOrganisationSchemeOperationCompleted == null)) {
                this.GetOrganisationSchemeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrganisationSchemeOperationCompleted);
            }
            this.InvokeAsync("GetOrganisationScheme", new object[] {
                        Any}, this.GetOrganisationSchemeOperationCompleted, userState);
        }
        
        private void OnGetOrganisationSchemeOperationCompleted(object arg) {
            if ((this.GetOrganisationSchemeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrganisationSchemeCompleted(this, new GetOrganisationSchemeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetProvisionAgreement", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetProvisionAgreement([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetProvisionAgreement", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetProvisionAgreementAsync(System.Xml.XmlElement Any) {
            this.GetProvisionAgreementAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetProvisionAgreementAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetProvisionAgreementOperationCompleted == null)) {
                this.GetProvisionAgreementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProvisionAgreementOperationCompleted);
            }
            this.InvokeAsync("GetProvisionAgreement", new object[] {
                        Any}, this.GetProvisionAgreementOperationCompleted, userState);
        }
        
        private void OnGetProvisionAgreementOperationCompleted(object arg) {
            if ((this.GetProvisionAgreementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProvisionAgreementCompleted(this, new GetProvisionAgreementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetConstraint", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetConstraint([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetConstraint", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetConstraintAsync(System.Xml.XmlElement Any) {
            this.GetConstraintAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetConstraintAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetConstraintOperationCompleted == null)) {
                this.GetConstraintOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConstraintOperationCompleted);
            }
            this.InvokeAsync("GetConstraint", new object[] {
                        Any}, this.GetConstraintOperationCompleted, userState);
        }
        
        private void OnGetConstraintOperationCompleted(object arg) {
            if ((this.GetConstraintCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConstraintCompleted(this, new GetConstraintCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetStructures", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetStructures([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetStructures", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetStructuresAsync(System.Xml.XmlElement Any) {
            this.GetStructuresAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetStructuresAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetStructuresOperationCompleted == null)) {
                this.GetStructuresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStructuresOperationCompleted);
            }
            this.InvokeAsync("GetStructures", new object[] {
                        Any}, this.GetStructuresOperationCompleted, userState);
        }
        
        private void OnGetStructuresOperationCompleted(object arg) {
            if ((this.GetStructuresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStructuresCompleted(this, new GetStructuresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/SubmitSubscription", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SubmitSubscription([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("SubmitSubscription", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitSubscriptionAsync(System.Xml.XmlElement Any) {
            this.SubmitSubscriptionAsync(Any, null);
        }
        
        /// <remarks/>
        public void SubmitSubscriptionAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.SubmitSubscriptionOperationCompleted == null)) {
                this.SubmitSubscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitSubscriptionOperationCompleted);
            }
            this.InvokeAsync("SubmitSubscription", new object[] {
                        Any}, this.SubmitSubscriptionOperationCompleted, userState);
        }
        
        private void OnSubmitSubscriptionOperationCompleted(object arg) {
            if ((this.SubmitSubscriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitSubscriptionCompleted(this, new SubmitSubscriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/QuerySubscription", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void QuerySubscription([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("QuerySubscription", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void QuerySubscriptionAsync(System.Xml.XmlElement Any) {
            this.QuerySubscriptionAsync(Any, null);
        }
        
        /// <remarks/>
        public void QuerySubscriptionAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.QuerySubscriptionOperationCompleted == null)) {
                this.QuerySubscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerySubscriptionOperationCompleted);
            }
            this.InvokeAsync("QuerySubscription", new object[] {
                        Any}, this.QuerySubscriptionOperationCompleted, userState);
        }
        
        private void OnQuerySubscriptionOperationCompleted(object arg) {
            if ((this.QuerySubscriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuerySubscriptionCompleted(this, new QuerySubscriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/SubmitRegistration", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SubmitRegistration([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("SubmitRegistration", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitRegistrationAsync(System.Xml.XmlElement Any) {
            this.SubmitRegistrationAsync(Any, null);
        }
        
        /// <remarks/>
        public void SubmitRegistrationAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.SubmitRegistrationOperationCompleted == null)) {
                this.SubmitRegistrationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitRegistrationOperationCompleted);
            }
            this.InvokeAsync("SubmitRegistration", new object[] {
                        Any}, this.SubmitRegistrationOperationCompleted, userState);
        }
        
        private void OnSubmitRegistrationOperationCompleted(object arg) {
            if ((this.SubmitRegistrationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitRegistrationCompleted(this, new SubmitRegistrationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/QueryRegistration", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void QueryRegistration([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("QueryRegistration", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void QueryRegistrationAsync(System.Xml.XmlElement Any) {
            this.QueryRegistrationAsync(Any, null);
        }
        
        /// <remarks/>
        public void QueryRegistrationAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.QueryRegistrationOperationCompleted == null)) {
                this.QueryRegistrationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryRegistrationOperationCompleted);
            }
            this.InvokeAsync("QueryRegistration", new object[] {
                        Any}, this.QueryRegistrationOperationCompleted, userState);
        }
        
        private void OnQueryRegistrationOperationCompleted(object arg) {
            if ((this.QueryRegistrationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryRegistrationCompleted(this, new QueryRegistrationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetGenericData", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetGenericData([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetGenericData", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetGenericDataAsync(System.Xml.XmlElement Any) {
            this.GetGenericDataAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetGenericDataAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetGenericDataOperationCompleted == null)) {
                this.GetGenericDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGenericDataOperationCompleted);
            }
            this.InvokeAsync("GetGenericData", new object[] {
                        Any}, this.GetGenericDataOperationCompleted, userState);
        }
        
        private void OnGetGenericDataOperationCompleted(object arg) {
            if ((this.GetGenericDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGenericDataCompleted(this, new GetGenericDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetGenericTimeSeriesData", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetGenericTimeSeriesData([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetGenericTimeSeriesData", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetGenericTimeSeriesDataAsync(System.Xml.XmlElement Any) {
            this.GetGenericTimeSeriesDataAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetGenericTimeSeriesDataAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetGenericTimeSeriesDataOperationCompleted == null)) {
                this.GetGenericTimeSeriesDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGenericTimeSeriesDataOperationCompleted);
            }
            this.InvokeAsync("GetGenericTimeSeriesData", new object[] {
                        Any}, this.GetGenericTimeSeriesDataOperationCompleted, userState);
        }
        
        private void OnGetGenericTimeSeriesDataOperationCompleted(object arg) {
            if ((this.GetGenericTimeSeriesDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGenericTimeSeriesDataCompleted(this, new GetGenericTimeSeriesDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetStructureSpecificData", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetStructureSpecificData([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetStructureSpecificData", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetStructureSpecificDataAsync(System.Xml.XmlElement Any) {
            this.GetStructureSpecificDataAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetStructureSpecificDataAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetStructureSpecificDataOperationCompleted == null)) {
                this.GetStructureSpecificDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStructureSpecificDataOperationCompleted);
            }
            this.InvokeAsync("GetStructureSpecificData", new object[] {
                        Any}, this.GetStructureSpecificDataOperationCompleted, userState);
        }
        
        private void OnGetStructureSpecificDataOperationCompleted(object arg) {
            if ((this.GetStructureSpecificDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStructureSpecificDataCompleted(this, new GetStructureSpecificDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetStructureSpecificTimeSeriesData", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetStructureSpecificTimeSeriesData([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetStructureSpecificTimeSeriesData", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetStructureSpecificTimeSeriesDataAsync(System.Xml.XmlElement Any) {
            this.GetStructureSpecificTimeSeriesDataAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetStructureSpecificTimeSeriesDataAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetStructureSpecificTimeSeriesDataOperationCompleted == null)) {
                this.GetStructureSpecificTimeSeriesDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStructureSpecificTimeSeriesDataOperationCompleted);
            }
            this.InvokeAsync("GetStructureSpecificTimeSeriesData", new object[] {
                        Any}, this.GetStructureSpecificTimeSeriesDataOperationCompleted, userState);
        }
        
        private void OnGetStructureSpecificTimeSeriesDataOperationCompleted(object arg) {
            if ((this.GetStructureSpecificTimeSeriesDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStructureSpecificTimeSeriesDataCompleted(this, new GetStructureSpecificTimeSeriesDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinfo.info/GetGenericMetadata", RequestNamespace="http://www.devinfo.info/", ResponseNamespace="http://www.devinfo.info/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetGenericMetadata([System.Xml.Serialization.XmlAnyElementAttribute()] ref System.Xml.XmlElement Any) {
            object[] results = this.Invoke("GetGenericMetadata", new object[] {
                        Any});
            Any = ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetGenericMetadataAsync(System.Xml.XmlElement Any) {
            this.GetGenericMetadataAsync(Any, null);
        }
        
        /// <remarks/>
        public void GetGenericMetadataAsync(System.Xml.XmlElement Any, object userState) {
            if ((this.GetGenericMetadataOperationCompleted == null)) {
                this.GetGenericMetadataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGenericMetadataOperationCompleted);
            }
            this.InvokeAsync("GetGenericMetadata", new object[] {
                        Any}, this.GetGenericMetadataOperationCompleted, userState);
        }
        
        private void OnGetGenericMetadataOperationCompleted(object arg) {
            if ((this.GetGenericMetadataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGenericMetadataCompleted(this, new GetGenericMetadataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetStructureSpecificMetadataCompletedEventHandler(object sender, GetStructureSpecificMetadataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStructureSpecificMetadataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStructureSpecificMetadataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SubmitStructureCompletedEventHandler(object sender, SubmitStructureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitStructureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitStructureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetReportingTaxonomyCompletedEventHandler(object sender, GetReportingTaxonomyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportingTaxonomyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportingTaxonomyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetStructureSetCompletedEventHandler(object sender, GetStructureSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStructureSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStructureSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetProcessCompletedEventHandler(object sender, GetProcessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProcessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProcessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetHierarchicalCodelistCompletedEventHandler(object sender, GetHierarchicalCodelistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHierarchicalCodelistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHierarchicalCodelistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDataSchemaCompletedEventHandler(object sender, GetDataSchemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataSchemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataSchemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMetadataSchemaCompletedEventHandler(object sender, GetMetadataSchemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMetadataSchemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMetadataSchemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDataflowCompletedEventHandler(object sender, GetDataflowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataflowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataflowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMetadataflowCompletedEventHandler(object sender, GetMetadataflowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMetadataflowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMetadataflowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDataStructureCompletedEventHandler(object sender, GetDataStructureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataStructureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataStructureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMetadataStructureCompletedEventHandler(object sender, GetMetadataStructureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMetadataStructureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMetadataStructureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCategorySchemeCompletedEventHandler(object sender, GetCategorySchemeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCategorySchemeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCategorySchemeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCategorisationCompletedEventHandler(object sender, GetCategorisationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCategorisationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCategorisationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetConceptSchemeCompletedEventHandler(object sender, GetConceptSchemeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConceptSchemeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConceptSchemeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCodelistCompletedEventHandler(object sender, GetCodelistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCodelistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCodelistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetOrganisationSchemeCompletedEventHandler(object sender, GetOrganisationSchemeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrganisationSchemeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrganisationSchemeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetProvisionAgreementCompletedEventHandler(object sender, GetProvisionAgreementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProvisionAgreementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProvisionAgreementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetConstraintCompletedEventHandler(object sender, GetConstraintCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConstraintCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConstraintCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetStructuresCompletedEventHandler(object sender, GetStructuresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStructuresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStructuresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SubmitSubscriptionCompletedEventHandler(object sender, SubmitSubscriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitSubscriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitSubscriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void QuerySubscriptionCompletedEventHandler(object sender, QuerySubscriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuerySubscriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuerySubscriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SubmitRegistrationCompletedEventHandler(object sender, SubmitRegistrationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitRegistrationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitRegistrationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void QueryRegistrationCompletedEventHandler(object sender, QueryRegistrationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryRegistrationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryRegistrationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGenericDataCompletedEventHandler(object sender, GetGenericDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGenericDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGenericDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGenericTimeSeriesDataCompletedEventHandler(object sender, GetGenericTimeSeriesDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGenericTimeSeriesDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGenericTimeSeriesDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetStructureSpecificDataCompletedEventHandler(object sender, GetStructureSpecificDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStructureSpecificDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStructureSpecificDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetStructureSpecificTimeSeriesDataCompletedEventHandler(object sender, GetStructureSpecificTimeSeriesDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStructureSpecificTimeSeriesDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStructureSpecificTimeSeriesDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGenericMetadataCompletedEventHandler(object sender, GetGenericMetadataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGenericMetadataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGenericMetadataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Any {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591