SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

---Add SortingOrder Column in the Areas table
IF NOT EXISTS(SELECT * FROM sys.columns where Name = N'SortingOrder' and Object_ID = Object_ID(N'Areas'))
Begin 
ALTER TABLE Areas ADD SortingOrder int;
EXEC ('
UPDATE  Areas SET SortingOrder=1 WHERE AreaName=''Global'' ;
UPDATE  Areas SET SortingOrder=2 WHERE AreaName=''Regional'';
UPDATE  Areas SET SortingOrder=11 WHERE AreaName !=''Global'' AND AreaName!=''Regional'' ;
');
END

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_GET_ADAPTATION_AREAS]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'
CREATE PROC [dbo].[SP_GET_ADAPTATION_AREAS]
	@AdaptationGUID NVARCHAR(4000)
AS
BEGIN 
	DECLARE @ADPT_AREA_NID INT

	SET @ADPT_AREA_NID = (SELECT AREA_NID FROM ADAPTATIONS WHERE [GUID] = @AdaptationGUID)

 IF @ADPT_AREA_NID = -1
  BEGIN
   SELECT * FROM (
   SELECT TOP 10000 AREANID, AREANAME, AREAID, PARENTNID,SortingOrder FROM AREAS 
    WHERE PARENTNID = -1   
    ORDER BY AREANAME) A
    UNION ALL
   SELECT * FROM (
    SELECT TOP 10000 AREANID, AREANAME, AREAID, PARENTNID,SortingOrder 
    FROM AREAS
    WHERE AREALEVEL = 2 AND AREANID IN (SELECT DISTINCT AREA_NID FROM ADAPTATIONS WHERE AREA_NID > 0)
    ORDER BY SortingOrder, AREANAME
   ) B
  END
 ELSE
  BEGIN
   SELECT AREANID, AREANAME, AREAID, PARENTNID,SortingOrder FROM AREAS 
   WHERE AREANID = @ADPT_AREA_NID OR PARENTNID = @ADPT_AREA_NID
   ORDER BY SortingOrder,AREANAME
  END
END
' 
END
ELSE
BEGIN
EXEC dbo.sp_executesql @statement = N'

ALTER PROC [dbo].[SP_GET_ADAPTATION_AREAS]
	@AdaptationGUID NVARCHAR(4000)
AS
BEGIN 
	DECLARE @ADPT_AREA_NID INT

	SET @ADPT_AREA_NID = (SELECT AREA_NID FROM ADAPTATIONS WHERE [GUID] = @AdaptationGUID)

 IF @ADPT_AREA_NID = -1
  BEGIN
   SELECT * FROM (
   SELECT TOP 10000 AREANID, AREANAME, AREAID, PARENTNID,SortingOrder FROM AREAS 
    WHERE PARENTNID = -1   
    ORDER BY AREANAME) A
    UNION ALL
   SELECT * FROM (
    SELECT TOP 10000 AREANID, AREANAME, AREAID, PARENTNID,SortingOrder 
    FROM AREAS
    WHERE AREALEVEL = 2 AND AREANID IN (SELECT DISTINCT AREA_NID FROM ADAPTATIONS WHERE AREA_NID > 0)
    ORDER BY SortingOrder, AREANAME
   ) B
  END
 ELSE
  BEGIN
   SELECT AREANID, AREANAME, AREAID, PARENTNID,SortingOrder FROM AREAS 
   WHERE AREANID = @ADPT_AREA_NID OR PARENTNID = @ADPT_AREA_NID
   ORDER BY SortingOrder,AREANAME
  END
END
' 
END
GO