//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevInfo.Lib.DI_LibBAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.devinfo.info/DI6WorldWideWebService/UserRegistration.asmx")]
        public string DI_LibBAL_DIWWSRegistration_UserRegistration {
            get {
                return ((string)(this["DI_LibBAL_DIWWSRegistration_UserRegistration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.devinfo.info/DI6WorldWideWebService/UserOnlineStatus.asmx")]
        public string DI_LibBAL_DIWWSStatus_UserOnlineStatus {
            get {
                return ((string)(this["DI_LibBAL_DIWWSStatus_UserOnlineStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.devinfo.info/DI6WorldWideWebService/Utility.asmx")]
        public string DI_LibBAL_DIWWSUtility_Utility {
            get {
                return ((string)(this["DI_LibBAL_DIWWSUtility_Utility"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.devinfo.org/di7webservices/Utility.asmx")]
        public string DI7_LibBAL_DIMapServerWS_Utility {
            get {
                return ((string)(this["DI7_LibBAL_DIMapServerWS_Utility"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.devinfo.org/libraries/ws/Registryservice.asmx")]
        public string DI7_LibBAL_SDMXRegistry_RegistryService {
            get {
                return ((string)(this["DI7_LibBAL_SDMXRegistry_RegistryService"]));
            }
        }
    }
}
