//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMXApi_2_0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDMXApi_2_0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2005  -   www.sdmx.org --&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common&quot; elementFormDefault=&quot;qualified&quot; xmlns=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;!-- Note: The following import statement sometimes causes problems with IE 6.* If you have this problem, comment it out. --&gt;
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot; schemaL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXCommon {
            get {
                return ResourceManager.GetString("SDMXCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2005  -   www.sdmx.org --&gt;
        ///&lt;xs:schema 
        ///  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///  elementFormDefault=&quot;qualified&quot; 
        ///  xmlns=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/compact&quot; 
        ///  xmlns:compact=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/compact&quot; 
        ///xmlns:common=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common&quot; 
        ///  targetNamespace=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/compact&quot;&gt;
        ///
        ///&lt;xs:import namespace=&quot;ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXCompactData {
            get {
                return ResourceManager.GetString("SDMXCompactData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2005  -   www.sdmx.org --&gt;
        ///&lt;xs:schema 
        ///  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///  elementFormDefault=&quot;qualified&quot; 
        ///  xmlns=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/cross&quot; 
        ///  xmlns:cross=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/cross&quot; 
        ///xmlns:common=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common&quot; 
        ///  targetNamespace=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/cross&quot;&gt;
        ///
        ///&lt;xs:import namespace=&quot;http://www [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXCrossSectionalData {
            get {
                return ResourceManager.GetString("SDMXCrossSectionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2005  -   www.sdmx.org --&gt;
        ///&lt;xs:schema 
        ///  targetNamespace=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/generic&quot; 
        ///  xmlns:generic=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/generic&quot; 
        ///  xmlns=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/generic&quot; 
        ///  xmlns:common=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common&quot; 
        ///  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xs:annotation&gt;
        ///		&lt;xs:docu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXGenericData {
            get {
                return ResourceManager.GetString("SDMXGenericData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///Copyright (c) SDMX 2005
        ///All rights reserved.
        ///http://www.sdmx.org
        ///--&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/genericmetadata&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/genericmetadata&quot; xmlns:common=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXGenericMetadata {
            get {
                return ResourceManager.GetString("SDMXGenericMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2005  -   www.sdmx.org --&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message&quot; xmlns:message=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message&quot; xmlns:structure=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure&quot; xmlns:generic=&quot;http://www.SDMX.org/resources [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXMessage {
            get {
                return ResourceManager.GetString("SDMXMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2005  -   www.sdmx.org --&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/metadatareport&quot; xmlns=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/metadatareport&quot; xmlns:common=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common&quot; schemaLocation=&quot;SDMXCommon. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXMetadataReport {
            get {
                return ResourceManager.GetString("SDMXMetadataReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2005  -   www.sdmx.org --&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; xmlns=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/query&quot; xmlns:query=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/query&quot; xmlns:common=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common&quot; targetNamespace=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/query&quot;&gt;
        ///
        ///&lt;xs:import namespace=&quot;http://www.SDMX.org/resources/SD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXQuery {
            get {
                return ResourceManager.GetString("SDMXQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- 
        ///
        ///Copyright (c) SDMX 2005
        ///All rights reserved.
        ///http://www.sdmx.org
        ///
        ///
        ///
        ///--&gt;
        ///
        ///&lt;xs:schema targetNamespace=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry&quot; xmlns:common=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common&quot; xmlns:structure=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure&quot; &gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXRegistry {
            get {
                return ResourceManager.GetString("SDMXRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2004  -   www.sdmx.org --&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure&quot; xmlns:structure=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure&quot; xmlns:common=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.SDMX.o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXStructure {
            get {
                return ResourceManager.GetString("SDMXStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright SDMX 2004  -   www.sdmx.org --&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///           elementFormDefault=&quot;qualified&quot; xmlns=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/utility&quot; 
        ///           xmlns:common=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common&quot; 
        ///           xmlns:utility=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/utility&quot; 
        ///           targetNamespace=&quot;http://www.SDMX.org/resources/SDMXML/schemas/v2_0/utility [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDMXUtilityData {
            get {
                return ResourceManager.GetString("SDMXUtilityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos;?&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.w3.org/XML/1998/namespace&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xml:lang=&quot;en&quot;&gt;
        ///
        /// &lt;xs:annotation&gt;
        ///  &lt;xs:documentation&gt;
        ///   See http://www.w3.org/XML/1998/namespace.html and
        ///   http://www.w3.org/TR/REC-xml for information about this namespace.
        ///  &lt;/xs:documentation&gt;
        /// &lt;/xs:annotation&gt;
        ///
        /// &lt;xs:annotation&gt;
        ///  &lt;xs:documentation&gt;This schema defines attributes and an attribute group
        ///	suitable for use by
        ///	schemas wishing to allow xml:base, x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml {
            get {
                return ResourceManager.GetString("xml", resourceCulture);
            }
        }
    }
}
