//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevInfo.Lib.DI_LibBAL.UI.Presentations.Map {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DIBShapes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DIBShapes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevInfo.Lib.DI_LibBAL.UI.Presentations.Map.DIBShapes", typeof(DIBShapes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_afr_Egypt_polygon_dbf {
            get {
                object obj = ResourceManager.GetObject("dib_afr_Egypt_polygon_dbf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_afr_Egypt_polygon_shp {
            get {
                object obj = ResourceManager.GetObject("dib_afr_Egypt_polygon_shp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_afr_Egypt_polygon_shx {
            get {
                object obj = ResourceManager.GetObject("dib_afr_Egypt_polygon_shx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_afr_Egypt_Sudan_line_dbf {
            get {
                object obj = ResourceManager.GetObject("dib_afr_Egypt_Sudan_line_dbf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_afr_Egypt_Sudan_line_shp {
            get {
                object obj = ResourceManager.GetObject("dib_afr_Egypt_Sudan_line_shp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_afr_Egypt_Sudan_line_shx {
            get {
                object obj = ResourceManager.GetObject("dib_afr_Egypt_Sudan_line_shx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_afr_Kenya_Sudan_line_dbf {
            get {
                object obj = ResourceManager.GetObject("dib_afr_Kenya_Sudan_line_dbf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_afr_Kenya_Sudan_line_shp {
            get {
                object obj = ResourceManager.GetObject("dib_afr_Kenya_Sudan_line_shp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_afr_Kenya_Sudan_line_shx {
            get {
                object obj = ResourceManager.GetObject("dib_afr_Kenya_Sudan_line_shx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_afr_Sudan_polygon_dbf {
            get {
                object obj = ResourceManager.GetObject("dib_afr_Sudan_polygon_dbf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_afr_Sudan_polygon_shp {
            get {
                object obj = ResourceManager.GetObject("dib_afr_Sudan_polygon_shp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_afr_Sudan_polygon_shx {
            get {
                object obj = ResourceManager.GetObject("dib_afr_Sudan_polygon_shx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_asi_1kashmir_polygon_dbf {
            get {
                object obj = ResourceManager.GetObject("dib_asi_1kashmir_polygon_dbf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_asi_1kashmir_polygon_shp {
            get {
                object obj = ResourceManager.GetObject("dib_asi_1kashmir_polygon_shp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_asi_1kashmir_polygon_shx {
            get {
                object obj = ResourceManager.GetObject("dib_asi_1kashmir_polygon_shx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_asi_ind_chn_polygon_dbf {
            get {
                object obj = ResourceManager.GetObject("dib_asi_ind_chn_polygon_dbf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_asi_ind_chn_polygon_shp {
            get {
                object obj = ResourceManager.GetObject("dib_asi_ind_chn_polygon_shp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_asi_ind_chn_polygon_shx {
            get {
                object obj = ResourceManager.GetObject("dib_asi_ind_chn_polygon_shx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_asi_ind_pak_loc_line_dbf {
            get {
                object obj = ResourceManager.GetObject("dib_asi_ind_pak_loc_line_dbf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_asi_ind_pak_loc_line_shp {
            get {
                object obj = ResourceManager.GetObject("dib_asi_ind_pak_loc_line_shp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_asi_ind_pak_loc_line_shx {
            get {
                object obj = ResourceManager.GetObject("dib_asi_ind_pak_loc_line_shx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_asi_Korea_armistice_line_dbf {
            get {
                object obj = ResourceManager.GetObject("dib_asi_Korea_armistice_line_dbf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_asi_Korea_armistice_line_shp {
            get {
                object obj = ResourceManager.GetObject("dib_asi_Korea_armistice_line_shp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_asi_Korea_armistice_line_shx {
            get {
                object obj = ResourceManager.GetObject("dib_asi_Korea_armistice_line_shx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_asi_PSE_line_dbf {
            get {
                object obj = ResourceManager.GetObject("dib_asi_PSE_line_dbf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_asi_PSE_line_shp {
            get {
                object obj = ResourceManager.GetObject("dib_asi_PSE_line_shp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dib_asi_PSE_line_shx {
            get {
                object obj = ResourceManager.GetObject("dib_asi_PSE_line_shx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DIBSettings xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;DIBLayersSetting&gt;
        ///    &lt;DIBLayerSetting&gt;
        ///      &lt;LayerName&gt;dib_asi_1kashmir_polygon&lt;/LayerName&gt;
        ///      &lt;FillStyle&gt;Solid&lt;/FillStyle&gt;
        ///      &lt;BorderStyle&gt;Dash&lt;/BorderStyle&gt;
        ///      &lt;BorderWidth&gt;0.01&lt;/BorderWidth&gt;
        ///      &lt;BorderColor&gt;-2894893&lt;/BorderColor&gt;
        ///      &lt;FillColor&gt;-2894893&lt;/FillColor&gt;
        ///    &lt;/DIBLayerSetting&gt;
        ///    &lt;DIBLayerSetting&gt;
        ///      &lt;LayerName&gt;dib_asi_ind_chn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DIBCurrent_xml {
            get {
                return ResourceManager.GetString("DIBCurrent_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DIBSettings xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;DIBLayersSetting&gt;
        ///    &lt;DIBLayerSetting&gt;
        ///      &lt;LayerName&gt;dib_asi_1kashmir_polygon&lt;/LayerName&gt;
        ///      &lt;FillStyle&gt;Solid&lt;/FillStyle&gt;
        ///      &lt;BorderStyle&gt;Dash&lt;/BorderStyle&gt;
        ///      &lt;BorderWidth&gt;0.01&lt;/BorderWidth&gt;
        ///      &lt;BorderColor&gt;-2894893&lt;/BorderColor&gt;
        ///      &lt;FillColor&gt;-2894893&lt;/FillColor&gt;
        ///    &lt;/DIBLayerSetting&gt;
        ///    &lt;DIBLayerSetting&gt;
        ///      &lt;LayerName&gt;dib_asi_ind_chn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DIBDefault_xml {
            get {
                return ResourceManager.GetString("DIBDefault_xml", resourceCulture);
            }
        }
    }
}
